web:
    build: web
    volumes:
        - web:/code
    ports:
        - "80:5000"
    links:
        - redis
        - rethinkdb
    command: python app.py

redis:
    restart: always
    image: redis:2.8.19
    ports:
        - "6379:6379"

rethinkdb:
    restart: always
    image: rethinkdb
